### ISSUE TITLE
[feature request] add the width='container' like in notebooks

### ISSUE THREAD

**Issue by bayees** [altair-viz/dash-vega-components#8]
like seen if creating chart in a Jupyter Notebook , It would be nice to have the ability the scale the chart to width of the container.

**Comment by binste** [comment]
Luckily, this is already possible, just not that well documented :) (it's one of the charts in [example_app.py])

In addition to using `width='container'` on the Altair chart object, you also have to set `style={"width": "100%"}` on the `dvc.Vega` object:

```python
dvc.Vega(
    id="altair-chart",
    style={"width": "100%"},
)
```

Does that solve it for you?

**Comment by bayees** [comment]
That did the job. Thank you. !

**Comment by bayees** [comment]
That did the job. Thank you. !
